### ISSUE TITLE
Build faalt vaak (onterecht) op een test van de Datepicker

### ISSUE THREAD

**Issue by gofix** [dso-toolkit/dso-toolkit#1416]
Soms faalt de test "should padStart days and months with 0" van de datepicker, zelfs als er niets gewijzigd is daar. Dat werkt sterk verstorend in het ontwikkelproces, en het is wenselijk dat deze test voorspelbaarder gaat werken.

**Comment by gofix** [comment]
```  1 failing
  1) Date Picker
       should padStart days and months with 0:
     CypressError: `cy.screenshot()` timed out waiting `30000ms` to complete.
      at http://localhost:56106/__cypress/runner/cypress_runner.js:160456:81
      at tryCatcher (http://localhost:56106/__cypress/runner/cypress_runner.js:13196:23)
      at http://localhost:56106/__cypress/runner/cypress_runner.js:8318:41
      at tryCatcher (http://localhost:56106/__cypress/runner/cypress_runner.js:13196:23)
      at Promise._settlePromiseFromHandler (http://localhost:56106/__cypress/runner/cypress_runner.js:11131:31)
      at Promise._settlePromise (http://localhost:56106/__cypress/runner/cypress_runner.js:11188:18)
      at Promise._settlePromise0 (http://localhost:56106/__cypress/runner/cypress_runner.js:11233:10)
      at Promise._settlePromises (http://localhost:56106/__cypress/runner/cypress_runner.js:11309:18)
      at _drainQueueStep (http://localhost:56106/__cypress/runner/cypress_runner.js:7903:12)
      at _drainQueue (http://localhost:56106/__cypress/runner/cypress_runner.js:7896:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:56106/__cypress/runner/cypress_runner.js:7912:5)
      at Async.drainQueues (http://localhost:56106/__cypress/runner/cypress_runner.js:7782:14)
      ```

**Comment by gofix** [comment]
Werkt, en brengt vast veel verlichting in ons leven.
De changelog entry werk ik nog wel bij als de release uitkomt.
