### ISSUE TITLE
Console error logging tooltip rootNode geen document of shadowRoot

### ISSUE THREAD

**Issue by Mennowm** [dso-toolkit/dso-toolkit#1963]
Er is geen reproductiepad en komt zelden voor. In overleg besloten een issue aan te maken zodat hij op de radar blijft. Op een paar momenten zagen we in de console logging de volgende error voorbij komen:

```
index.js:3101 Error: rootNode is not instance of Document or ShadowRoot
    at push../node_modules/@dso-toolkit/core/dist/components/tooltip.js.Tooltip.descriptive.getTarget (tooltip.js:2006:1)
    at push../node_modules/@dso-toolkit/core/dist/components/tooltip.js.Tooltip.descriptive.componentDidLoad (tooltip.js:1965:1)
    at safeCall (index.js:1929:1)
    at postUpdateComponent (index.js:1846:1)
    at updateComponent (index.js:1776:1)
    at index.js:1708:1
    at then (index.js:1938:1)
    at dispatchHooks (index.js:1708:1)
    at Array.dispatch (index.js:1676:1)
    at consume (index.js:3201:1) undefined
consoleError @ index.js:3101
```

**Comment by hansgrimm** [comment]
Gaat naar backlog; IP kan deze ook niet reproduceren.

**Comment by tfrijsewijk** [comment]
@svrijsewijk Is dit niet dat probleem dat we zouden oplossen door het Web Component stil te laten falen?

**Comment by LukeVerlaan** [comment]
Dit is inderdaad het probleem dat nu met stil falen is opgelost. Die branch staat niks van waarde in.

**Comment by MichielDHVD** [comment]
Dit is opgelost @LukeVerlaan  gaat kijken in welke issue dit is opgelost en sluit dit issue.

**Comment by LukeVerlaan** [comment]
Dit is opgelost in het issue #2101.
