### ISSUE TITLE
Ozon Content: flaky e2e test

### ISSUE THREAD

**Issue by iterox** [dso-toolkit/dso-toolkit#2789]
Sinds deze aanpassing/toevoeging aan `storybook/cypress/support/commands.ts`
```
/**
 * This overwrite tries to wait for all fonts to load before taking the screenshot.
 *
 * See #2748 for more information.
 */
Cypress.Commands.overwrite("screenshot", (originalFn, ...args) => {
  return cy
    .document()
    .its("fonts.status")
    .should("equal", "loaded")
    .then(() => originalFn(...args));
});
```
faalt in de buildstraat de CICD op

```
{
  test: 'Ozon Content - should render renvooi-weergave elements (cypress/e2e/ozon-content.cy.ts)',
  error: 'CypressError: `cy.then()` timed out after waiting `4000ms`.\n' +
    '\n' +
    'Your callback function returned a promise that never resolved.\n' +
    '\n' +
    'The callback function was:\n' +
    '\n' +
    '() => originalFn(...args)\n' +
    '\n' +
    'https://on.cypress.io/then\n' +
    '    at <unknown> (http://localhost:45000/__cypress/runner/cypress_runner.js:119257:75)\n' +
    '    at tryCatcher (http://localhost:45000/__cypress/runner/cypress_runner.js:1807:23)\n' +
    '    at <unknown> (http://localhost:45000/__cypress/runner/cypress_runner.js:4186:41)\n' +
    '    at tryCatcher (http://localhost:45000/__cypress/runner/cypress_runner.js:1807:23)\n' +
    '    at Promise._settlePromiseFromHandler (http://localhost:45000/__cypress/runner/cypress_runner.js:1519:31)\n' +
    '    at Promise._settlePromise (http://localhost:45000/__cypress/runner/cypress_runner.js:1576:18)\n' +
    '    at Promise._settlePromise0 (http://localhost:45000/__cypress/runner/cypress_runner.js:1621:10)\n' +
    '    at Promise._settlePromises (http://localhost:45000/__cypress/runner/cypress_runner.js:1697:18)\n' +
    '    at _drainQueueStep (http://localhost:45000/__cypress/runner/cypress_runner.js:2407:12)\n' +
    '    at _drainQueue (http://localhost:45000/__cypress/runner/cypress_runner.js:2400:9)\n' +
    '    at Async._drainQueues (http://localhost:45000/__cypress/runner/cypress_runner.js:2416:5)\n' +
    '    at Async.drainQueues (http://localhost:45000/__cypress/runner/cypress_runner.js:2286:14)\n' +
    'From Your Spec Code:\n' +
    '    at Context.eval (webpack://dso-storybook/./cypress/support/commands.ts:55:0)'
}
```

Mogelijk conflicteren deze 2 overrides in `storybook/cypress/support/commands.ts`:

```
Cypress.Commands.overwrite("screenshot", (originalFn, ...args) => {
  return cy
    .document()
    .its("fonts.status")
    .should("equal", "loaded")
    .then(() => originalFn(...args));
});
```

```
Cypress.Commands.overwrite("visit", (originalFn, url, options) => {
  // @ts-expect-error -- https://github.com/cypress-io/cypress/issues/19564
  return originalFn(url, options).then(() => {
    cypressStyling();
  });
});
```

**Comment by iterox** [comment]
Ik heb de `matchImageSnapshot` ff losgetrokken van de oorspronkelijk test. En als ik dan `yarn build-www` en `yarn e2e` draai dan krijg ik een vreemd resultaat:

<img width="2526" alt="Screenshot 2024-10-11 at 16 51 11" src="https://github.com/user-attachments/assets/a2da257b-7b3a-49e1-af9a-916736448058">

de ene test `should matchImageSnapshot renvooi-weergave elements` resulteert in 2 screenshots...

Mogelijk is dit een lead.
